### ISSUE TITLE
Trying to register method which returns std::unique_ptr

### ISSUE THREAD

**Issue by chanon** [rttrorg/rttr#10]
Hello, 

I have a class which has a method that returns a std::unique_ptr. It basically constructs an object and gives ownership back to the caller using the std::unique_ptr to transfer ownership.

It uses std::move inside when returning.

The problem is while trying to register this method I get the error:

Error	C2338	The given value is not copy constructible, try to add a copy constructor to the class.	rttr\detail\variant\variant_impl.h	56	

Maybe a new method policy for this might work?

**Comment by acki-m** [comment]
The returned type from an invoke of a `method` is a `variant`, which requires that the contained type is copy able. However the `std::unique_ptr<T>` is not copy able. That's why you are getting the error message. It's not enough the move the type in the `variant`, because the `variant`itself can be copied.

I recommend to return a `std::shared_ptr<T>` or maybe a raw ptr.

However, when you really need to return a `unique_ptr<T>`, you can make a wrapper class for move-only types, which can copy the `unique_ptr<T>`. In the namespace of `rttr::detail` is such a wrapper class.

Be warned that this can lead to strange behavior. 

```
#include <rttr/registration>
#include <memory>

struct foo_bar
{
    static detail::move_wrapper<std::unique_ptr<foo_bar>> create()
    {
        return detail::make_rref(detail::make_unique<foo_bar>());
    }
};

RTTR_REGISTRATION
{
    registration::class_<foo_bar>("foo_bar")
        .method("create", &foo_bar::create);

    variant var2;
    {
        variant var1 = type::get_by_name("foo_bar").invoke("create", instance(), {});
        var2 = var1; // var1 is still valid, but the unique_ptr inside is empty after the assignment
    }
}
```
Remark: do not use anything from `rttr:.detail`. Its just an example.

**Comment by chanon** [comment]
After thinking about it some more, I guess it is a bit strange to use std::unique_ptr in this case.
