### ISSUE TITLE
get_class_method iterates over all methods which is slow

### ISSUE THREAD

**Issue by mfojtak** [rttrorg/rttr#12]
When a user needs to call a method having it's string name, then this would be called:

for (; itr != m_class_method_list.cend(); ++itr)
    {
        auto& item = *itr;
        if (item.m_class_id != raw_type.get_id())
            break;

        if (item.m_name_hash != name_hash)
            break;

        if (std::strcmp(item.m_data->get_name(), name) == 0)
            return item.m_data.get();
    }
This is slow. Qt does it by generating a switch statement. The overhead could be solved with modern c++1x as well.

**Comment by mfojtak** [comment]
Moc generates this for qt_static_metacall:
switch (_id) {
        case 0: call some method(); break;
        .....
        default: ;
        }
Where the _id is int. But if you access methods via array index like so get_methods()[_id] then the performance would be the same anyway. Having method string name requires to find the method first to be able to call it. I am trying to figure out how to optimize it. You're right - hashes would work, however I could not find any hashed vectors in type_database_p.h.

My usecase is that I want to wrap my c++ classes or even classes from other libraries into some reflection wrapper (like your's or ponder).
And then having that I want to generate Python/Qt(using QMetaObjectBuilder)/NodeJS runtime bindings.
I cannot use Qt because it requires to decorate the class itself. You approach is more clever from this point of view.

**Comment by acki-m** [comment]
This generated code is for invoking a method, not for retrieving.
The question is why do you need to retrieve the method that faster? Is it because of the missing default constructor of `method`? You should retrieve the method one time and invoke it then multiple times.

[Here](https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/type/type_database_p.h#L240) is the code for sorting the vector.

Maybe I can make the method/property/constructor default constructable. Have to think about this.

**Comment by mfojtak** [comment]
Well, if you want to invoke a method or set a property, you need to retrieve it first.
Btw, why don't you use std::unordered_map for method/property lookup?

I have a few other questions/suggestions but don't now what is the right forum for this.
Question:
  - would it make sense to have rttr header only? What would be pros and cons?
Suggestion:
  - implement callback registrations. E.g. register std::function(lambda) which would be invoked when:
        - property is set
        - method invoked
        - new instance created (constructor called)

I can go ahead and fork rttr and implement it myself however I need to know if the above makes sense or is it out of scope of rttr.

**Comment by acki-m** [comment]
Regarding the names: For my use cases I never retrieve a property or a method via its name. i think this is also the normal case for others. E.g. when you want to serialize a type, you want to retrieve all properties not only a certain one. Or when you want to bind your type to a scripting engine, you want to bind every method, not only a certain one.

At the moment I am working on branch [add_range_based_views](https://github.com/rttrorg/rttr/tree/add_range_based_views) to return ranges instead of vectors. Which avoids the dynamic memory allocation and should be much faster.

1)
I would love to make RTTR header only, but its not possible.
The reason is because of the instantiation of static variables in libraries.
You can read more about it in following article: http://www.axelmenzel.de/articles/rtti#custom_type_info

2)
Please open for this a new issue on github. So we can discuss there, Its sound like a signal-slot alternative. 
With the flexible registration process this is easily possible:
```
RTTR_REGISTRATION
{
   rttr::registration<foo>("foo")
            .property("prop", &foo::prop)
            ( 
                metadata("label", "some description"),
                callback([](){std::cout << "property was invoked.\n"; })
            );
}
```
This registration process is static, there is no interaction between object.
So, I don't know how useful this is, It seems to me out of scope for a reflection engine.
But maybe you can convince me.

PS: is there some kind of vote mechanism in github?

**Comment by mfojtak** [comment]
Regarding the header only issue and your point 1:
There is the std::type_index type (see http://en.cppreference.com/w/cpp/types/type_index) which is there exactly for the purpose that you need. Or was there another reason to implement the custom_type_info?

I will create a new issue for the meta-callbacks and see if can convince you :-)

**Comment by acki-m** [comment]
yeah, there is a reason: http://www.axelmenzel.de/articles/rtti#introduction

**Comment by mfojtak** [comment]
yes, but I am not talking about std::type_info but about std::type_index.

Your comment: "Another drawback is that the type_info objects are not copyable. That means it is not possible to use them directly in a container. Creating a wrapper class around type_info object will fix this issue."

But that's why there is std::type_index :
"The type_index class is a wrapper class around a std::type_info object, that can be used as index in associative and unordered associative containers. The relationship with type_info object is maintained through a pointer, therefore type_index is CopyConstructible and CopyAssignable."

**Comment by acki-m** [comment]
Yeah, and i also mentioned in the following sentence that you can create a wrapper for that.
However, typeid lacks other problems too:
> In some special situation the typeid operator doesn't work, more precisely there are problems when used [across shared boundaries](https://svn.boost.org/trac/boost/ticket/754).


The other thing is, there are platforms, where RTTI is not available. This library can help there.
When you satisfied, with the answer, please close the issue. And open a new Issue for you're callback request.
