### ISSUE TITLE
standard policy should be std::unique_ptr

### ISSUE THREAD

**Issue by gabyx** [rttrorg/rttr#157]
the default ctor should by default return a `std::unique_ptr`. 
The reasoning is that one can release a
`std::unique_ptr` and do whatever you want with it, where as you cannot with a `std::shared_ptr`.
The usecase is that one needs to specially change the policy to `policy::ctor::as_raw_ptr` and wrap it into the `std::unique_ptr`. The default behavior, when `type::create`is called that it should return a `std::unique_ptr` (if the ctor policy is defaulted) is in my opinion by far more consistent. Also in accordance to a factory which also should return a std::unique_ptr, why force the user to use std::shared_ptr?

**Comment by acki-m** [comment]
A `std::unique_ptr` cannot be copied. That's why I cannot return it with a [rttr::variant](http://www.rttr.org/doc/master/classrttr_1_1variant.html). The only way to make this possible would be to use a new return type for constructors. But then you would be inconsistent with the all other return types (e.g. methods, properties, ...).
What is the bad about using `std::shared_ptr` or the other policy: `policy::ctor::as_raw_ptr`?

**Comment by acki-m** [comment]
@gabyx 
What about the `policy::ctor::as_raw_ptr`?

**Comment by gabyx** [comment]
Jeah, is definitely ok, but its not the default policy, which I kind of understand now.

**Comment by acki-m** [comment]
When it would be the default policy, you would always have to delete it. I close this Issue now.
But when you come up with a solution to the problem, feel free to post it here.
