### ISSUE TITLE
Incorrect behavior of rttr::library load<->unload<->load sequence 

### ISSUE THREAD

**Issue by bsviglo** [rttrorg/rttr#162]
It looks like the is difference between **load<->unload<->load** sequence and **load<->destructor of library<->constructor of library<->load**.
In the first sequence we have some garbage rttr::type-s while the second sequence works perfectly fine.

**Comment by acki-m** [comment]
Please provide a test case.
Remark, to throw away every handle to types of the loaded library after you unload it.

**Comment by bsviglo** [comment]
Hi, after some experiments I've found out that the my initial thought that **load<->destructor of library<->constructor of library<->load** helps is wrong.
Invoking destructor doesn't help me to solve the problem because under the hood you store all library objects till the end of the program and the actual hot-reloading isn't happening.
So using unload method is the right way to go. 

In any way thanks for the very great library.

**Comment by acki-m** [comment]
What do you mean how hot reloading should work?
You load the library, store the state of all types in an intermediate format, then unload the library, throw away all handles to created types, then load the new version of the library and create the types depending on the stored state again.

When this problem is solved for you, feel free to close it.
