### ISSUE TITLE
Is there a way to directly get the instance of a property?

### ISSUE THREAD

**Issue by rovingstar** [rttrorg/rttr#165]
code like following:

```
class C
{
public:
    float m_f;
    ...
};

class B
{
public:
    C m_c;
    ...
};

class A
{
public:
    B m_b;
    ...
};


void func()
{
    rttr::property b_prop = rttr::get_type<A>().get_property("m_b");
    rttr::property c_prop = rttr::get_type<B>().get_property("m_c");
    rttr::property f_prop = rttr::get_type<C>().get_property("m_f");

    A a;

    //set a.b.c.f to 1.2f through reflection
    rttr::variant a_b = b_prop.get_value(a);
    rttr::variant b_c = c_prop.get_value(a_b);
    f_prop.set_value(b_c, 1.2f);
    c_prop.set_value(a_b, b_c);
    b_prop.set_value(a, a_b);
}

```
is there a way to get the instance(reference) of an object's property?  something like 
rttr::instance rttr::property::get_property_instance(rttr::instance object)

so we can avoid all theses value copies?

**Comment by acki-m** [comment]
From a property, you will get always a `variant` as return value. This variant will always copy the data.
However, you can register your properties while using [policies](http://www.rttr.org/doc/master/structrttr_1_1policy_1_1prop.html#a6e551c5748cfaad0d8f1afc353817f78)
When you use the `reference_wrapper` policy the value will be copies as `std::reference_wrapper` in the variant. So no copy at all. And because `rttr;;variant` has a small object optimization, there will be no dynamic memory allocation. Does this help?

**Comment by rovingstar** [comment]
Yes, that's exactly what I'm looking for.  Thank you very much!
