### ISSUE TITLE
Retrieving class properties underlying type

### ISSUE THREAD

**Issue by gouletr** [rttrorg/rttr#177]
Is there any way to get the value of a property without knowing its underlying type? The method `variant::get_value()` is a function template that requires the class member type, which kind of defeat the purpose of the registration?

```cpp
struct Foo {
    int bar;
};

RTTR_REGISTRATION {
    rttr::registration::class_<Foo>("Foo")
        .property("bar", &Foo::bar);
}

void serialize(Stream& stream, int& value) {
    // serialize int value...
}

void serialize(Stream& stream, Foo& foo) {
    auto type = rttr::type::get<Foo>();
    for (auto& prop : type.get_properties()) {
        auto name = prop.get_name();
        auto var = prop.get_value(foo);
        stream.serialize(name, var.get_value</* here how to get Foo::bar original type? */>());
    }
}
```

Perhaps there is a way to store metadata along each property to store its underlying type? I'm looking for whatever solution that works, could be metadata, plugin, anything!

Thanks

**Comment by acki-m** [comment]
You can do following:
```
void serialize(Stream& stream, Foo& foo) {
    auto type = rttr::type::get<Foo>();
    for (auto& prop : type.get_properties()) {
        auto name = prop.get_name();
        auto var = prop.get_value(foo);
        if (var.get_type() == type::get<int>())
        stream.serialize(name, var.to_int());
      else if (var.get_type() == type::get<double>())
        stream.serialize(name, var.to_double());
     else if (....)
    }
}
```
Does this help?

**Comment by gouletr** [comment]
No unfortunately, the type is unknown at the time I need to get the member value. And anyway how would that work for my own types? I would have expected `variant` to be a template class, so that `get_value()` doesn't require we pass a type.

**Comment by acki-m** [comment]
@gouletr 
When variant it would be a class template, RTTR would not work how it works. 
Because with RTTR you can work with types, which are unknown at compile time. You don't even need the header file. `variant::get_value<T>` is a function template. there you can provide your needed type.
However, you can always register functions so that the variant can convert to these types. E.g. providing a function which converts your custom type to a std::string.
Then you could simply write: `stream.serialize(name, var.to_string());`
See:
[type::register_converter_func](https://www.rttr.org/doc/master/classrttr_1_1type.html#a81f5f2ea31cc79846a829aa5737680f0)

**Comment by gouletr** [comment]
Yes I get that right now RTTR works with types that are unknown at compile time. But my point is that it would be nice if it also supported types that **are** known at compile time, so that we can iterate through members with types preserved. Right now the type erasure is a major drawback imho.

**Comment by acki-m** [comment]
@gouletr 
Actually, its not a major draw back. It's a missing feature. Because having the possibility to work with unknown types is one of RTTR's major feature.
However, I have a PR https://github.com/rttrorg/rttr/pull/154 ready to merge (after some more added unit tests), which basically allows you to do what you want. Iterate over all members of an object at compile time. Right, that is what you want?

**Comment by gouletr** [comment]
Yes, this is what I need. Can you share a snippet of what the code will look like? Your PR is quite massive.

**Comment by acki-m** [comment]
There is an scripting example and a unit test for it. Take a look here:
Test:
https://github.com/rttrorg/rttr/pull/154/files#diff-94c545f2663bcabce4f5ce5fc027fd65
Scripting:
https://github.com/rttrorg/rttr/pull/154/files#diff-6d632bcaf15bd4e69c4fe2c9c82130ff

**Comment by acki-m** [comment]
Done. It's now merged and ready to used. See the examples and the unit test for more information.
