### ISSUE TITLE
RTTR_REGISTRATION never invoked

### ISSUE THREAD

**Issue by DerGaijin** [rttrorg/rttr#245]
Hello
i am using your library (static) in my own library (static) and maybe that doesn't have to do anything but if i create a .cpp file in my library just for registering some classes (only auto RTTR_REGISTRATION) the function never gets invoked so the classes are not registered..
maybe its the compiler (Visual Studio 15 2017) who says the file is empty and not building it in my library
Just wanna let you know :)

**Comment by vamidi** [comment]
It might be that your header and source file are not being compiled, because they are not needed. if you registrate a class you need to make sure you are exactly using it. try using inside main.cpp `new class()`
also include `std::cout` for testing purposes. you can see in the console if the compiler is doing something with your registration.

```RTTR_REGISTRATION
{
	std::cout << "Creating reflection for: className" << std::endl;
```
