### ISSUE TITLE
rttr and dlls.

### ISSUE THREAD

**Issue by volcoma** [rttrorg/rttr#41]
I have a question. If i have some classes with reflection in my app. Then load a .dll with other classes with reflection. Will the ones loaded from a dll be available for me? Or can i somehow introduce their reflection data to my app?

**Comment by acki-m** [comment]
When your app and the loaded DLL linked against the same version of RTTR you will have to reflection information available. No matter whether it is loaded explicitly or implicit.

**Comment by volcoma** [comment]
ok then when my app doesnt link against the rttr, but the dll does, then can i still use the reflection data from the dll?

**Comment by acki-m** [comment]
Of course not, that's not possible in C++ at all. Think about RTTR as wrapper around your library, you have to have access to the wrapper otherwise it won't work.
However, when you would make a C wrapper around my library, I think you would be able to explicitly load RTTR and can then load also you library explicitly too.

**Comment by volcoma** [comment]
Thanks.
