### ISSUE TITLE
Thread-safety

### ISSUE THREAD

**Issue by MicBe** [rttrorg/rttr#74]
Is rttr thread-safe?

**Comment by acki-m** [comment]
The registration part is not 100% thread safe atm.
The only part what is missing, is a mutex in the registration function.

However, when you register your types inside [RTTR_REGISTRATION](http://www.rttr.org/doc/master/registration_8h.html#ac6326400f16225ee15b52eabcaae8130), it means all objects are initialized before `main` is called, and these calls are thread safe.

PS: I have not included the mutex, because some mingw setup has no native thread support (uses boost instead). So maybe I will add it
